language: go

service:
  - docker

go:
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.15.0

script:
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - env
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [ -n "$TRAVIS_TAG" ]; then make deploy; fi
